# from collections import deque 
# queue = deque(["Ram", "Tarun", "Asif", "John"]) 
# print(queue) 
# queue.append("Akbar") 
# print(queue) 
# queue.append("Birbal") 
# print(queue) 
# print(queue.popleft())                  
# print(queue.popleft())                  
# print(queue) 

from collections import deque
q1 = deque([100,25,3,45,32,37])
q2 = deque(["Rahul","sagar","345","deepak", 89])
# print(q1)
# print(q2)
q1.append("Hii")
q2.append('hello')
print(q1)
print(q2)
q1.popleft()
print(q1)
q2.popleft()
print(q2)
